# Dependencies
markdown:         kramdown
highlighter:      pygments


# Permalinks
permalink:        pretty

# Setup
title:            Mario Brendel
tagline:          'Blog About Angular2'
description:      'Blog About Angular2'
url:              http://mario-brendel.com
baseurl:          /
email:            mariob@mario-brendel.com

author:
  name:           Mario Brendel
  url:            mariob@mario-brendel.com

paginate:         5
gems:             [jekyll-paginate]
paginate_path:    "page:num"

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/MarioBrendel

feed:
  path: atom.xml
